### ISSUE TITLE
code gives wrong results with seemingly trivial changes to data's columns names

### ISSUE THREAD

**Issue by rdiaz02** [danro9685/HESBCN#3] opened 2023-09-14 09:02 UTC
The code gives NaNs when one makes trivial changes to column names. Using, for example, the ov.cgh data from package Oncotree (https://cran.r-project.org/web/packages/Oncotree/index.html), having column names "A1,B2,C,D,E,F,G" leads to trouble, but "A1,B,C,D,E,F,G" doesn't. Limited testing suggests that if two or more column names have more than one character, the program gets confused. 

Reproducible examples (see files attached, that differ only on the column names; the data are the ov.cgh data from package Oncotree ---https://cran.r-project.org/web/packages/Oncotree/index.html)
[d3.txt](https://github.com/danro9685/HESBCN/files/12606900/d3.txt)
[d2.txt](https://github.com/danro9685/HESBCN/files/12606901/d2.txt)
[d1.txt](https://github.com/danro9685/HESBCN/files/12606902/d1.txt)

```
# OK
h-esbcn -d d1.txt -o ox.txt -n 1000 -s 1
# NaN
h-esbcn -d d2.txt -o ox.txt -n 1000 -s 1
# NaN
h-esbcn -d d3.txt -o ox.txt -n 1000 -s 1
```

**Comment by luca-dex** [comment] 2023-10-17 09:31
The problem is in the function `read_patterns`:

```
int len = getline(&line, &temp, input);
	if (len != -1) {
		n = len / 2;
```

 This function calculate as the number of events `n` half of the amount of characters of the first line of the input file. I'll fix it asap

**Comment by danro9685** [comment] 2023-10-17 10:51
Fixed with latest pull request.

**Closed as completed by danro9685** 2023-10-17 10:51 UTC
